before_script:
    - pip install --user mkdocs

script:
    - mkdocs build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: docs.kittcar.com
  acl: public_read
  on:
    repo: kittcar/kitt_docs
  skip_cleanup: true
  region: $AWS_DEFAULT_REGION
  local_dir: site
