site_name: kitt_docs
theme: readthedocs
pages:
    - Home: index.md
    - Donkey Simulator: donkey_sim.md
    - Sustainability: sustainability.md
    - Improvements: improvements.md
    - Style: style.md
    - Wikis: wikis.md
    - Tests: tests.md
